### PR TITLE
feat: add trends tab

### PR DESCRIPTION
**Pull request by elrrrrrrr**
> 参照 https://npmtrends.com/next 实现下载趋势对比, see #75 
1. 默认全量展示 2020 年开始相关数据
2. 支持最多5个包横向对比

image

## Summary by CodeRabbit

- **New Features**
	- Introduced a "Download Trends" tab to provide insights into the download trends of packages.
	- Added a new `Trends` component that allows users to view and compare the total downloads of multiple packages over different years.
	- Implemented functionality to search for packages and display their total download statistics on the Trends page.

### CODE REVIEW

**Review by fengmk2 — APPROVED** [review]
+1

**Comment by fengmk2** [comment]
npm cli 已经被超越

**Comment by fengmk2** [comment]
@elrrrrrrr 啊，我测试了一下，对比 url 不会变化？没法将当前对比结果链接分享出去。

**Comment by elrrrrrrr** [comment]
> @elrrrrrrr 啊，我测试了一下，对比 url 不会变化？没法将当前对比结果链接分享出去。

😄 我一会儿加下

**Pull request merged**
